language: java
sudo: false
script:
  - mvn clean compile
  - mvn test -B
  - mvn package assembly:single
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file:
    - target/testing-*.zip
  skip_cleanup: true
  on:
    tags: true
